name: Sync Fork

on:
  schedule:
    - cron: '* */24 * * *' # every 30 minutes
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: FongMi/CatVodSpider
        with:
          owner: tvfuns
          base: master
          head: master
